- name: Create a new local content library
  vmware.vmware_rest.content_locallibrary:
    vcenter_hostname: "{{ vcenter_hostname | default(omit) }}"
    vcenter_username: "{{ vcenter_username | default(omit) }}"
    vcenter_password: "{{ vcenter_password | default(omit) }}"
    vcenter_validate_certs: "{{ vcenter_validate_certs | default(omit) }}"
    id:                 "{{ item.id   | default(omit) }}"
    type:               "{{ item.type | default(omit) }}"
    name:               "{{ item.name | default(omit) }}"
    state:              "{{ item.state   }}"
    version:            "{{ item.version | default(omit) }}"
    library_id:         "{{ item.library_id     | default(omit) }}"
    server_guid:        "{{ item.server_guid    | default(omit) }}"
    description:        "{{ item.description    | default(omit) }}"
    publish_info:       "{{ item.publish_info   | default(omit) }}"
    subscriptions:      "{{ item.subscriptions  | default(omit) }}"
    last_sync_time:     "{{ item.last_sync_time | default(omit) }}"
    session_timeout:    "{{ item.session_timeout    | default(omit) }}"
    storage_backings:   "{{ item.storage_backings   | default(omit) }}"
    subscription_info:  "{{ item.subscription_info  | default(omit) }}"
    optimization_info:  "{{ item.optimization_info  | default(omit) }}"
    security_policy_id: "{{ item.security_policy_id | default(omit) }}"
    last_modified_time: "{{ item.last_modified_time | default(omit) }}"
    unset_security_policy_id: "{{ item.unset_security_policy_id | default(omit) }}"
    vcenter_rest_log_file:    "{{ item.vcenter_rest_log_file    | default(omit) }}"
    client_token:             "{{ item.client_token  | default(omit) }}"
    creation_time:            "{{ item.creation_time | default(omit) }}"
    library_id:               "{{ item.library_id    | default(omit) }}"
  register: primary_content_library

- block:
  - name: grab content library info
    vmware.vmware_rest.content_locallibrary_info:
      library_id: "{{ primary_content_library['id'] }}"
    register: primary_content_library_info

  - set_fact:
      subscription_info:
        subscription_url: "{{ primary_content_library_info['value']['publish_info']['publish_url'] }}"
        authentication_method: NONE
        on_demand: true
        automatic_sync_enabled: true
      library_id: "{{ primary_content_library_info['value'].id }}"
  when: item.state | lower == 'present'

- include_tasks: content_library_subscriber.yml
  with_items: "{{ item.content_library_subscriber }}"
  loop_control:
    loop_var: library
  when: run
  vars:
    run: "{{ (item.content_library_subscriber is defined) | ternary(true, false)}}"