- name: Create a new subscribed content library
  vmware.vmware_rest.content_subscribedlibrary:
    vcenter_hostname: "{{ vcenter_hostname | default(omit) }}"
    vcenter_username: "{{ vcenter_username | default(omit) }}"
    vcenter_password: "{{ vcenter_password | default(omit) }}"
    vcenter_validate_certs: "{{ vcenter_validate_certs | default(omit) }}"
    id:                 "{{ library.id | default(omit) }}"
    type:               "{{ library.type | default(omit) }}"
    name:               "{{ library.name }}"
    state:              "{{ library.state   | default(omit) }}"
    version:            "{{ library.version | default(omit) }}"
    library_id:         "{{ library.library_id     | default(omit) }}"
    server_guid:        "{{ library.server_guid    | default(omit) }}"
    description:        "{{ library.description    | default(omit) }}"
    publish_info:       "{{ library.publish_info   | default(omit) }}"
    subscriptions:      "{{ library.subscriptions  | default(omit) }}"
    last_sync_time:     "{{ library.last_sync_time | default(omit) }}"
    session_timeout:    "{{ library.session_timeout    | default(omit) }}"
    storage_backings:   "{{ library.storage_backings   | default(omit) }}"
    subscription_info:  "{{ subscription_info  | default(omit) }}"
    optimization_info:  "{{ library.optimization_info  | default(omit) }}"
    security_policy_id: "{{ library.security_policy_id | default(omit) }}"
    last_modified_time: "{{ library.last_modified_time | default(omit) }}"
    authentication_method:    "{{ library.authentication_method | default(omit) }}"
    unset_security_policy_id: "{{ library.unset_security_policy_id | default(omit) }}"
    vcenter_rest_log_file:    "{{ library.vcenter_rest_log_file | default(omit) }}"
    client_token:             "{{ library.client_token  | default(omit) }}"
    creation_time:            "{{ library.creation_time | default(omit) }}"
    library_id:               "{{ library.library_id | default(omit) }}"
  register: sub_lib
  delegate_to: localhost

- name: trigger a sync
  vmware.vmware_rest.content_subscribedlibrary:
    vcenter_hostname: "{{ vcenter_hostname | default(omit) }}"
    vcenter_username: "{{ vcenter_username | default(omit) }}"
    vcenter_password: "{{ vcenter_password | default(omit) }}"
    vcenter_validate_certs: "{{ vcenter_validate_certs | default(omit) }}"
    name: "{{ library.name }}"
    library_id: '{{ sub_lib.id }}'
    state: sync
  delegate_to: localhost